name: Upload artifact to Station307

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Upload bin to Station307
        run: |
          if [ -f pay.x64.bin ]; then
            curl -T pay.x64.bin -s -L -D - xfr.station307.com | grep human
          else
            echo "⚠️ File pay.x64.bin not found"
          fi
